export {default as Header} from './layout/header/Header';
export {default as Footer} from './layout/footer/Footer';
export {default as SocialIcons} from './SocialIcons/SocialIcons';
export {default as BlueFilledBtn} from './custom-buttons/BlueFilledBtn/BlueFilledBtn';
export {default as BlueOulinedBtn} from './custom-buttons/BlueOulinedBtn/BlueOulinedBtn';
export {default as IconBtn} from './custom-buttons/IconBtn/IconBtn';
export {default as CustomCard} from './CustomCard/CustomCard'; 
export {default as SectionalHeading} from './SectionalHeading/SectionalHeading';
export {default as TermsNCondition} from './TermsNCondition/TermsNCondition';
export {default as CommonHero} from './CommonHero/CommonHero';
export {default as BlogSidebar} from './BlogSidebar/BlogSidebar';
export {default as CommonSidebar} from './CommonSidebar/CommonSidebar';
export {default as InterestFree} from './InterestFree/InterestFree';
export {default as BookAndCall} from './BookAndCall/BookAndCall';
export {default as PPCHeader} from './layout/PPCHeader/PPCHeader';
export {default as PPCBanner} from './PPCBanner/PPCBanner';
export {default as PPCFooter} from './layout/PPCFooter/PPCFooter'